In [6]:
import numpy as np
import pandas as pd

In [2]:
def ackley(x):
    """
    Computes the d-dimensional Ackley function.
    :param x: np.array, shape (d,) - point at which to evaluate the function.
    :return: float - value of the Ackley function at x.
    """
    a = 20
    b = 0.2
    c = 2 * np.pi
    d = len(x)
    sum1 = -a * np.exp(-b * np.sqrt(np.sum(x ** 2) / d))
    sum2 = -np.exp(np.sum(np.cos(c * x)) / d)
    return sum1 + sum2 + a + np.exp(1)

In [3]:

def create_ackley_tensor(dimensions, lower_bound=-5, upper_bound=5):
    """
    Creates a tensor where each entry contains the Ackley function's evaluation at corresponding points in the search space.
    :param dimensions: int - dimensionality of the search space.
    :param lower_bound: int - lower bound for the search space.
    :param upper_bound: int - upper bound for the search space.
    :return: np.ndarray - tensor of Ackley function evaluations across the search space.
    """
    # Generate ranges for each dimension
    ranges = [np.arange(lower_bound, upper_bound + 1) for _ in range(dimensions)]
    
    # Create a meshgrid for the search space
    mesh = np.meshgrid(*ranges, indexing='ij')
    
    # Stack the meshgrid to create coordinates for each point in the search space
    grid_points = np.stack(mesh, axis=-1)
    
    # Compute the Ackley function at each point in the grid
    ackley_values = np.apply_along_axis(ackley, -1, grid_points)
    
    return ackley_values

# Example usage:
ackley_tensor = create_ackley_tensor(dimensions=2)
print("Ackley tensor for a 2D search space:\n", ackley_tensor)

Ackley tensor for a 2D search space:
 [[1.26424112e+01 1.19135182e+01 1.12319788e+01 1.06614129e+01
  1.02757573e+01 1.01386262e+01 1.02757573e+01 1.06614129e+01
  1.12319788e+01 1.19135182e+01 1.26424112e+01]
 [1.19135182e+01 1.10134207e+01 1.01386262e+01 9.37428782e+00
  8.83663892e+00 8.64058576e+00 8.83663892e+00 9.37428782e+00
  1.01386262e+01 1.10134207e+01 1.19135182e+01]
 [1.12319788e+01 1.01386262e+01 9.02376728e+00 7.98891081e+00
  7.21185362e+00 6.91497816e+00 7.21185362e+00 7.98891081e+00
  9.02376728e+00 1.01386262e+01 1.12319788e+01]
 [1.06614129e+01 9.37428782e+00 7.98891081e+00 6.59359908e+00
  5.42213172e+00 4.92723367e+00 5.42213172e+00 6.59359908e+00
  7.98891081e+00 9.37428782e+00 1.06614129e+01]
 [1.02757573e+01 8.83663892e+00 7.21185362e+00 5.42213172e+00
  3.62538494e+00 2.63753109e+00 3.62538494e+00 5.42213172e+00
  7.21185362e+00 8.83663892e+00 1.02757573e+01]
 [1.01386262e+01 8.64058576e+00 6.91497816e+00 4.92723367e+00
  2.63753109e+00 4.44089210e-16 2.63753109e+00 4.92723367e+00
  6.91497816e+00 8.64058576e+00 1.01386262e+01]
 [1.02757573e+01 8.83663892e+00 7.21185362e+00 5.42213172e+00
  3.62538494e+00 2.63753109e+00 3.62538494e+00 5.42213172e+00
  7.21185362e+00 8.83663892e+00 1.02757573e+01]
 [1.06614129e+01 9.37428782e+00 7.98891081e+00 6.59359908e+00
  5.42213172e+00 4.92723367e+00 5.42213172e+00 6.59359908e+00
  7.98891081e+00 9.37428782e+00 1.06614129e+01]
 [1.12319788e+01 1.01386262e+01 9.02376728e+00 7.98891081e+00
  7.21185362e+00 6.91497816e+00 7.21185362e+00 7.98891081e+00
  9.02376728e+00 1.01386262e+01 1.12319788e+01]
 [1.19135182e+01 1.10134207e+01 1.01386262e+01 9.37428782e+00
  8.83663892e+00 8.64058576e+00 8.83663892e+00 9.37428782e+00
  1.01386262e+01 1.10134207e+01 1.19135182e+01]
 [1.26424112e+01 1.19135182e+01 1.12319788e+01 1.06614129e+01
  1.02757573e+01 1.01386262e+01 1.02757573e+01 1.06614129e+01
  1.12319788e+01 1.19135182e+01 1.26424112e+01]]

In [5]:
ackley_tensor.shape

(11, 11)

In [7]:
df = pd.DataFrame(ackley_tensor)

In [8]:
df

,0,1,2,3,4,5,6,7,8,9,10
0,12.642411,11.913518,11.231979,10.661413,10.275757,1.013863e+01,10.275757,10.661413,11.231979,11.913518,12.642411
1,11.913518,11.013421,10.138626,9.374288,8.836639,8.640586e+00,8.836639,9.374288,10.138626,11.013421,11.913518
2,11.231979,10.138626,9.023767,7.988911,7.211854,6.914978e+00,7.211854,7.988911,9.023767,10.138626,11.231979
3,10.661413,9.374288,7.988911,6.593599,5.422132,4.927234e+00,5.422132,6.593599,7.988911,9.374288,10.661413
4,10.275757,8.836639,7.211854,5.422132,3.625385,2.637531e+00,3.625385,5.422132,7.211854,8.836639,10.275757
5,10.138626,8.640586,6.914978,4.927234,2.637531,4.440892e-16,2.637531,4.927234,6.914978,8.640586,10.138626
6,10.275757,8.836639,7.211854,5.422132,3.625385,2.637531e+00,3.625385,5.422132,7.211854,8.836639,10.275757
7,10.661413,9.374288,7.988911,6.593599,5.422132,4.927234e+00,5.422132,6.593599,7.988911,9.374288,10.661413
8,11.231979,10.138626,9.023767,7.988911,7.211854,6.914978e+00,7.211854,7.988911,9.023767,10.138626,11.231979
9,11.913518,11.013421,10.138626,9.374288,8.836639,8.640586e+00,8.836639,9.374288,10.138626,11.013421,11.913518
10,12.642411,11.913518,11.231979,10.661413,10.275757,1.013863e+01,10.275757,10.661413,11.231979,11.913518,12.642411

In [9]:
print( df )

           0          1          2          3          4             5   \
0   12.642411  11.913518  11.231979  10.661413  10.275757  1.013863e+01
1   11.913518  11.013421  10.138626   9.374288   8.836639  8.640586e+00
2   11.231979  10.138626   9.023767   7.988911   7.211854  6.914978e+00
3   10.661413   9.374288   7.988911   6.593599   5.422132  4.927234e+00
4   10.275757   8.836639   7.211854   5.422132   3.625385  2.637531e+00
5   10.138626   8.640586   6.914978   4.927234   2.637531  4.440892e-16
6   10.275757   8.836639   7.211854   5.422132   3.625385  2.637531e+00
7   10.661413   9.374288   7.988911   6.593599   5.422132  4.927234e+00
8   11.231979  10.138626   9.023767   7.988911   7.211854  6.914978e+00
9   11.913518  11.013421  10.138626   9.374288   8.836639  8.640586e+00
10  12.642411  11.913518  11.231979  10.661413  10.275757  1.013863e+01

           6          7          8          9          10
0   10.275757  10.661413  11.231979  11.913518  12.642411
1    8.836639   9.374288  10.138626  11.013421  11.913518
2    7.211854   7.988911   9.023767  10.138626  11.231979
3    5.422132   6.593599   7.988911   9.374288  10.661413
4    3.625385   5.422132   7.211854   8.836639  10.275757
5    2.637531   4.927234   6.914978   8.640586  10.138626
6    3.625385   5.422132   7.211854   8.836639  10.275757
7    5.422132   6.593599   7.988911   9.374288  10.661413
8    7.211854   7.988911   9.023767  10.138626  11.231979
9    8.836639   9.374288  10.138626  11.013421  11.913518
10  10.275757  10.661413  11.231979  11.913518  12.642411